### PR TITLE
Typescript type definitions

### PR DESCRIPTION
**Pull request by Artur-A**

### CODE REVIEW

**Comment by AAllport** [comment]
any idea why this hasn't been merged?

**Comment by Artur-A** [comment]
cc @kenny-hibino, @AAllport 

not sure, almost forgot about this PR, it's very handy for Typescript users.

**Comment by AAllport** [comment]
Almost started writing the defs, then thought. Hmm, should probably check the pr's

**Comment by kenny-hibino** [comment]
@AAllport @Artur-A Hey guys! Thank you for using this component library.
I have personally never used TypeScript and not sure if I'm the right person to code review this pull request. I'll try to find time to take a look at all pending pull requests sometime in the next few months. But in the meantime, please use @Artur-A 's fork to use this in TypeScript 👍

**Comment by AAllport** [comment]
@Artur-A any reason why you have removed the dist folder from gitignore?

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325

(Happy to revisit this if anyone would like to update the PR and revert the change to gitignore that removes the dist folder)

**Pull request closed without merging**
