### PR TITLE
[WIP] Added soft autocomplete to input while typing

### PR DESCRIPTION
**Pull request by paulokuda**
AirBnb/Google chrome style autofill

### CODE REVIEW

**Comment by CoVoCre** [comment]
So why's this not merged or closed yet ? 😢

**Comment by paulokuda** [comment]
@hibiken What were the issues with this approach again? I forget 😆 

Anyways, I'm gonna close this PR for now.

**Comment by CoVoCre** [comment]
But @paulokuda , actually wasn't this a great feature ?!?! It's like the [highlightFirstSuggestion](https://github.com/hibiken/react-places-autocomplete#highlightFirstSuggestion) flag, except way better 😅

**Comment by paulokuda** [comment]
@CoVoCre Yes, it was a great feature; however, there were issues that @hibiken and I discussed offline -- will defer to him on this one.

**Comment by CoVoCre** [comment]
@paulokuda well, now, we can implement in our child function ! Like use a custom input text to which we pass the first suggestion as a "ghost" autocomple en of text !

**Pull request closed without merging**
