### PR TITLE
Added a onInput method

### PR DESCRIPTION
**Pull request by alvarosilvac**
Added an onInput method for editing directly the value of the input field. The component will be able also to retrieve the results with no necessity of the onChange method. (Will still working)

### CODE REVIEW

**Comment by CoVoCre** [comment]
Hmmm... @alvarosilvac , it seems here the [onInput](https://www.w3schools.com/jsref/event_oninput.asp) would behave exactly the same as onChange... Or in what case would it be different ?

**Comment by alvarosilvac** [comment]
I had this inconvenience of changing the value of the input field directly. I know is not a good practice to change the value of the element, but I was creating a virtual keyboard, and this was the best way that I found it possible. If you have another way to resolve this problem, I am open to it.

**Comment by CoVoCre** [comment]
I don't understand, you want to be able to change the value directly ? What do you mean by directly ? 😅
Why can't you just change the [value of the value field you pass to PlacesAutocomplete as a prop](https://github.com/hibiken/react-places-autocomplete/blob/master/README.md#value) ?

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325

**Pull request closed without merging**
