### PR TITLE
Ability to pass custom input field

### PR DESCRIPTION
**Pull request by chardmd**
Ability to pass custom input component like material ui field component as children.

### CODE REVIEW

**Comment by chardmd** [comment]
Now we can integrate material ui / react-toolbox by integrating this feature.

`            <PlacesAutocomplete
              onSelect={this.handleSelect}
              onError={onError}
              renderSuggestion={AutocompleteItem}
              onEnterKeyDown={this.handleSelect}
              classNames={cssClasses}
              inputProps={inputProps}
              shouldFetchSuggestions={shouldFetchSuggestions}
              renderFooter={Footer}
              hasCustomInput
            >
              <TextField
                label="Search Address"
                InputLabelProps={{
                  shrink: true,
                }}
                margin="normal"
                autoComplete="off"
                {...inputProps}
              />
            </PlacesAutocomplete>`

**Comment by chardmd** [comment]
We can now integrate material-ui or react toolbox or any other 3rd party input.

            <PlacesAutocomplete
              onSelect={this.handleSelect}
              onError={onError}
              renderSuggestion={AutocompleteItem}
              onEnterKeyDown={this.handleSelect}
              classNames={cssClasses}
              inputProps={inputProps}
              shouldFetchSuggestions={shouldFetchSuggestions}
              renderFooter={Footer}
              hasCustomInput
            >
              <TextField
                label="Search Address"
                InputLabelProps={{
                  shrink: true,
                }}
                margin="normal"
                autoComplete="off"
                {...inputProps}
              />
            </PlacesAutocomplete>

**Comment by gauravarora91** [comment]
Someone please merge this

**Comment by davejm** [comment]
@kenny-hibino

**Comment by nehvaleem** [comment]
Yeah, totally need this one!

**Comment by joshuaadickerson** [comment]
@hibiken any updates on this? I want to use this with MUI

**Comment by hibiken** [comment]
`react-places-autocomplete` made a major breaking change in v7.0.0, making API flexible to allow custom rendering of the UI. Please upgrade to v 7.x or above if you need to customize the rendering of your input.

**Comment by chardmd** [comment]
closing this pull request since the feature is now available in v7.x thanks everyone.

**Pull request closed without merging**
